# human_type = [
#     'Squire',
#     'Knight',
#     'Archer',
#     'Priest',
#     'Wizard',
#     'Thief',
#     'Druid',
#     'Red Dragon',
#     'Black Dragon',
# ]

human_type = {
    'Squire': {'name': 'Squire',
               'life': 250,
               'attack': 160,
               'defense': 60,
               'level': 6,
               'xp': 250,
               'crit_chance': 15},

    'Knight': {'name': 'Knight',
               'life': 350,
               'attack': 260,
               'defense': 85,
               'level': 11,
               'xp': 300,
               'crit_chance': 20},

    'Archer': {'name': 'Archer',
               'life': 380,
               'attack': 250,
               'defense': 75,
               'level': 12,
               'xp': 400,
               'crit_chance': 70},

    'Black Mage': {'name': 'Black Mage',
                   'life': 400,
                   'attack': 300,
                   'defense': 60,
                   'level': 13,
                   'xp': 500,
                   'crit_chance': 20},

    'Monk': {'name': 'Monk',
             'life': 500,
             'attack': 500,
             'defense': 50,
             'level': 14,
             'xp': 700,
             'crit_chance': 15},

    'Time Mage': {'name': 'Time Mage',
                  'life': 500,
                  'attack': 400,
                  'defense': 70,
                  'level': 15,
                  'xp': 800,
                  'crit_chance': 20},

    'Geomancer': {'name': 'Geomancer',
                  'life': 600,
                  'attack': 600,
                  'defense': 70,
                  'level': 16,
                  'xp': 850,
                  'crit_chance': 0},

    'Summoner': {'name': 'Summoner',
                 'life': 650,
                 'attack': 750,
                 'defense': 60,
                 'level': 17,
                 'xp': 950,
                 'crit_chance': 0},

    'Samurai': {'name': 'Samurai',
                'life': 1300,
                'attack': 700,
                'defense': 170,
                'level': 18,
                'xp': 1200,
                'crit_chance': 0},

    'Ninja': {'name': 'Ninja',
              'life': 900,
              'attack': 550,
              'defense': 130,
              'level': 19,
              'xp': 1200,
              'crit_chance': 40},

    'Dark Archer': {'name': 'Dark Archer',
                    'life': 1200,
                    'attack': 800,
                    'defense': 130,
                    'level': 20,
                    'xp': 1700,
                    'crit_chance': 80},

    'Dark Samurai': {'name': 'Dark Samurai',
                     'life': 2300,
                     'attack': 1000,
                     'defense': 250,
                     'level': 21,
                     'xp': 2000,
                     'crit_chance': 0}

}
